version: "3.2"
services: 
  db:
    build: server/database/
    expose:
      - 5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod
  api:
    build: server/
    expose: 
      - 8001
    depends_on: 
      - db
    env_file: 
      - ./.env.prod
  nginx:
    build: client/
    ports:
      - ${NGINX_PORT}:8000
    depends_on:
      - api